import type { ForgeConfig } from '@electron-forge/shared-types';
import { MakerSquirrel } from '@electron-forge/maker-squirrel';
import { MakerZIP } from '@electron-forge/maker-zip';
import { VitePlugin } from '@electron-forge/plugin-vite';
import { FusesPlugin } from '@electron-forge/plugin-fuses';
import { FuseV1Options, FuseVersion } from '@electron/fuses';
import packageJson from './package.json';

const VERSION = packageJson.version;
// Windows version resources need a numeric a.b.c.d FileVersion; a pre-release like 0.1.0-alpha.1
// keeps its full text in ProductVersion and gets FileVersion 0.1.0.<pre-release number>.
const [CORE_VERSION = VERSION, PRERELEASE = ''] = VERSION.split('-');
const BUILD_VERSION = `${CORE_VERSION}.${Number(PRERELEASE.match(/(\d+)$/)?.[1] ?? 0)}`;

// ---------------------------------------------------------------------------------------------
// PROVISIONAL IDENTITY. Everything below that names the product, the publisher or the install
// (app/Squirrel name, authors, company, app id, icon artwork) is a placeholder the owner must
// confirm or replace before any public release. See docs/release-process.md ("Owner actions").
// ---------------------------------------------------------------------------------------------
const PRODUCT_NAME = 'FrameCapt'; // PROVISIONAL
const PUBLISHER = 'FrameCapt contributors'; // PROVISIONAL
const DESCRIPTION = 'FrameCapt - an offline, Windows-first screenshot and screen recording app.';

// ---------------------------------------------------------------------------------------------
// Code signing: optional, from the environment ONLY. No certificate is ever committed.
//   WINDOWS_CERTIFICATE_FILE      path to an Authenticode .pfx
//   WINDOWS_CERTIFICATE_PASSWORD  its password
//   WINDOWS_TIMESTAMP_SERVER      optional (default http://timestamp.digicert.com, read by
//                                 @electron/windows-sign)
// Both variables set: the packaged exe/dll/node files (Packager `windowsSign`) and the Squirrel
// Setup.exe/Update.exe (maker `windowsSign`) are signed with signtool. Otherwise the build is
// UNSIGNED, and says so below: Windows SmartScreen will warn when it is run.
// ---------------------------------------------------------------------------------------------
const certificateFile = process.env.WINDOWS_CERTIFICATE_FILE?.trim();
const certificatePassword = process.env.WINDOWS_CERTIFICATE_PASSWORD;
const windowsSign =
  certificateFile && certificatePassword
    ? { certificateFile, certificatePassword, description: PRODUCT_NAME }
    : undefined;
if (!windowsSign && (certificateFile || certificatePassword)) {
  throw new Error(
    'Code signing is half configured: set both WINDOWS_CERTIFICATE_FILE and WINDOWS_CERTIFICATE_PASSWORD, or neither.',
  );
}
console.log(
  windowsSign
    ? `[framecapt] Windows code signing: ENABLED (certificate from WINDOWS_CERTIFICATE_FILE)`
    : '[framecapt] Windows code signing: DISABLED - this build is UNSIGNED (set WINDOWS_CERTIFICATE_FILE and WINDOWS_CERTIFICATE_PASSWORD to sign)',
);

const config: ForgeConfig = {
  packagerConfig: {
    name: PRODUCT_NAME,
    executableName: PRODUCT_NAME,
    // PROVISIONAL app id - owner must confirm before publication
    appBundleId: 'com.framecapt.app',
    buildVersion: BUILD_VERSION,
    // The owner's logo as an icon (assets/app/framecapt.ico, generated by npm run brand:assets).
    icon: 'assets/app/framecapt',
    win32metadata: {
      CompanyName: PUBLISHER, // PROVISIONAL
      FileDescription: DESCRIPTION,
      ProductName: PRODUCT_NAME,
      InternalName: PRODUCT_NAME,
      OriginalFilename: `${PRODUCT_NAME}.exe`,
      'requested-execution-level': 'asInvoker',
    },
    asar: true,
    // The pinned FFmpeg build (npm run fetch:ffmpeg, run by the prepackage/premake/prestart hooks).
    // extraResource copies the folder by its name: <resources>/ffmpeg/win32-x64/{ffmpeg,ffprobe}.exe.
    // LICENSE (GPL-3.0) and THIRD_PARTY_NOTICES.md ship next to Electron's own license files.
    extraResource: ['vendor/ffmpeg', 'LICENSE', 'THIRD_PARTY_NOTICES.md'],
    ...(windowsSign && { windowsSign }),
    // Pinned Electron zip checksum (from the official v44.5.1 SHASUMS256.txt, verified 2026-10-02).
    // Builds are reproducible and work from the local cache without re-fetching SHASUMS256.txt.
    // Update together with the electron version in package.json.
    download: {
      checksums: {
        'electron-v44.5.1-win32-x64.zip':
          '9b382492dcfee91f8f9e92c91f7972550a1b95d2299cac72279dab33a600d7db',
      },
    },
  },
  rebuildConfig: {},
  makers: [
    new MakerSquirrel({
      // The NuGet package id and the install folder (%LOCALAPPDATA%\FrameCapt). PROVISIONAL.
      name: PRODUCT_NAME,
      title: PRODUCT_NAME,
      authors: PUBLISHER, // PROVISIONAL
      description: DESCRIPTION,
      exe: `${PRODUCT_NAME}.exe`,
      // No spaces in the setup file name: safe in URLs, scripts and release assets.
      setupExe: `${PRODUCT_NAME}-Setup-${VERSION}.exe`,
      setupIcon: 'assets/app/framecapt.ico',
      // Shown by Setup.exe while it installs (interactive installs only; silent ones show nothing).
      loadingGif: 'assets/app/install-loading.gif',
      // No .msi: Squirrel's per-user Setup.exe is the installer (no admin rights, no UAC prompt).
      noMsi: true,
      // Squirrel downloads an iconUrl at install time (default: raw.githubusercontent.com), which
      // stalled an offline install for ~85 s. Our nuspec template has no iconUrl; Programs and
      // Features shows a generic icon until the owner hosts one (docs/release-process.md).
      nuspecTemplate: 'assets/app/framecapt.nuspectemplate',
      ...(windowsSign && { windowsSign }),
    }),
    // Portable zip: unzip anywhere and run FrameCapt.exe (no installer, no updates, no shortcuts).
    new MakerZIP({}, ['win32']),
  ],
  plugins: [
    new VitePlugin({
      // Main and preload bundles are emitted as .cjs by the plugin.
      build: [
        { entry: { main: 'src/main/index.ts' }, config: 'vite.main.config.ts', target: 'main' },
        {
          entry: { preload: 'src/preload/index.ts' },
          config: 'vite.preload.config.ts',
          target: 'preload',
        },
      ],
      renderer: [{ name: 'main_window', config: 'vite.renderer.config.ts' }],
    }),
    // Secure fuse set. Note: Playwright cannot drive a packaged build because
    // EnableNodeCliInspectArguments is off; e2e runs against .vite/build instead.
    new FusesPlugin({
      version: FuseVersion.V1,
      [FuseV1Options.RunAsNode]: false,
      [FuseV1Options.EnableCookieEncryption]: true,
      [FuseV1Options.EnableNodeOptionsEnvironmentVariable]: false,
      [FuseV1Options.EnableNodeCliInspectArguments]: false,
      [FuseV1Options.EnableEmbeddedAsarIntegrityValidation]: true,
      [FuseV1Options.OnlyLoadAppFromAsar]: true,
      // The renderer is served from app://framecapt, nothing loads from file:// (ADR-033, R-01), so
      // file:// pages do not need their extra privileges (fetch, service workers, ...).
      [FuseV1Options.GrantFileProtocolExtraPrivileges]: false,
    }),
  ],
};

export default config;
