import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { TRAY_ICONS, TRAY_SCALE_FACTORS } from '../../src/main/tray-icons.generated';

const root = path.resolve(__dirname, '..', '..');
const read = (...parts: string[]): Buffer => fs.readFileSync(path.join(root, ...parts));

/** Width and height from a PNG's IHDR chunk. */
function pngSize(png: Buffer): [number, number] {
  expect(png.subarray(1, 4).toString('latin1')).toBe('PNG');
  return [png.readUInt32BE(16), png.readUInt32BE(20)];
}

describe('brand assets (generated by npm run brand:assets, committed)', () => {
  it('has the transparent logo masters at 1024, 512 and 256 px', () => {
    for (const size of [1024, 512, 256]) {
      const file = size === 1024 ? 'framecapt-logo.png' : `framecapt-logo-${size}.png`;
      expect(pngSize(read('assets', 'brand', file))).toEqual([size, size]);
    }
    expect(fs.existsSync(path.join(root, 'assets', 'brand', 'framecapt-logo-source.png'))).toBe(
      true,
    );
  });

  it('has an app icon with every Windows size, the 256 px entry as a PNG', () => {
    const ico = read('assets', 'app', 'framecapt.ico');
    expect(ico.readUInt16LE(2)).toBe(1);
    const count = ico.readUInt16LE(4);
    const sizes: number[] = [];
    for (let i = 0; i < count; i += 1) {
      const width = ico[6 + i * 16] ?? 0;
      sizes.push(width === 0 ? 256 : width);
      const offset = ico.readUInt32LE(6 + i * 16 + 12);
      const length = ico.readUInt32LE(6 + i * 16 + 8);
      expect(pngSize(ico.subarray(offset, offset + length))).toEqual([sizes[i], sizes[i]]);
    }
    expect(sizes).toEqual([16, 20, 24, 32, 40, 48, 64, 128, 256]);
  });

  it('has an installer loading GIF within the size budget (400x300, looping)', () => {
    const gif = read('assets', 'app', 'install-loading.gif');
    expect(gif.subarray(0, 6).toString('latin1')).toMatch(/^GIF8[79]a$/);
    expect([gif.readUInt16LE(6), gif.readUInt16LE(8)]).toEqual([400, 300]);
    expect(gif.length).toBeLessThanOrEqual(1.5 * 1024 * 1024);
    expect(gif.includes(Buffer.from('NETSCAPE2.0'))).toBe(true);
  });

  it('has the tray icons at four scale factors, idle and recording, matching the embedded copy', () => {
    expect(TRAY_SCALE_FACTORS).toEqual({ 16: 1, 20: 1.25, 24: 1.5, 32: 2 });
    for (const variant of ['normal', 'recording'] as const) {
      for (const size of [16, 20, 24, 32] as const) {
        const embedded = Buffer.from(TRAY_ICONS[variant][size], 'base64');
        expect(pngSize(embedded)).toEqual([size, size]);
        const file = variant === 'normal' ? `tray-${size}.png` : `tray-recording-${size}.png`;
        expect(embedded.equals(read('assets', 'tray', file))).toBe(true);
      }
    }
    // The recording variant really differs from the idle one.
    expect(TRAY_ICONS.normal[16]).not.toBe(TRAY_ICONS.recording[16]);
  });

  it('has the renderer logo at 32, 64, 128 and 256 px', () => {
    for (const size of [32, 64, 128, 256]) {
      expect(pngSize(read('src', 'renderer', 'assets', `logo-${size}.png`))).toEqual([size, size]);
    }
  });
});
