/**
 * Integration with the REAL vendored ffmpeg/ffprobe (`npm run fetch:ffmpeg`): a WebM live stream
 * is generated by ffmpeg itself (VP9 + Opus, 5 s, `-live 1`, so like MediaRecorder output it has no
 * Duration and no Cues), cut into arbitrary chunks, written through the real session service,
 * finalized and probed/decoded. Skipped, with a message, when the binaries are not fetched.
 * Set FRAMECAPT_WRITE_EVIDENCE=1 to write docs/evidence/phase06/ffmpeg-integration.json.
 */
import { spawnSync } from 'node:child_process';
import http from 'node:http';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { DEFAULT_RECORD_OPTIONS } from '../../src/shared/recorder-ipc';
import { mp4Args } from '../../src/main/media/export';
import { createMediaTools, FfmpegError, resolveFfmpeg } from '../../src/main/media/ffmpeg';
import { RecoveryService } from '../../src/main/recording/recovery';
import { nodeSessionFs } from '../../src/main/recording/session-fs';
import { SessionService, type SessionConfig } from '../../src/main/recording/session-service';
import { writeEvidenceJson } from '../native/evidence';

const repoRoot = path.resolve(__dirname, '..', '..');
const location = { isPackaged: false, resourcesPath: '', appPath: repoRoot };
let paths: ReturnType<typeof resolveFfmpeg> | null = null;
try {
  paths = resolveFfmpeg(location);
} catch (error) {
  if (!(error instanceof FfmpegError)) throw error;
  console.warn(
    `SKIPPING ffmpeg integration tests: ${error.message} (vendor/ffmpeg/<platform>-<arch> is missing)`,
  );
}

const ID = '0f0e0d0c-0b0a-4908-8706-050403020100';
const CONFIG: SessionConfig = {
  mime: 'video/webm;codecs=vp9,opus',
  source: { kind: 'screen', name: 'Screen 1' },
  options: DEFAULT_RECORD_OPTIONS,
  width: 640,
  height: 360,
};

const evidence: Record<string, unknown> = {};

/** A deterministic pseudo-random sequence (so chunk boundaries are the same on every run). */
function lcg(seed: number): () => number {
  let state = seed;
  return () => {
    state = (state * 1664525 + 1013904223) % 4294967296;
    return state / 4294967296;
  };
}

function splitArbitrarily(bytes: Buffer, seed = 7): Buffer[] {
  const random = lcg(seed);
  const parts: Buffer[] = [];
  let offset = 0;
  while (offset < bytes.length) {
    const size = Math.max(1, Math.floor(random() * 40_000));
    parts.push(bytes.subarray(offset, Math.min(bytes.length, offset + size)));
    offset += size;
  }
  return parts;
}

describe.skipIf(paths === null)('real ffmpeg: finalization and recovery', () => {
  const tools = createMediaTools(() => resolveFfmpeg(location));
  let work: string;
  let live: Buffer;
  let counter = 0;

  beforeAll(() => {
    work = fs.mkdtempSync(path.join(os.tmpdir(), 'framecapt-ffint-'));
    const run = spawnSync(
      paths?.ffmpeg ?? '',
      [
        '-hide_banner',
        '-v',
        'error',
        '-f',
        'lavfi',
        '-i',
        'testsrc=size=640x360:rate=30',
        '-f',
        'lavfi',
        '-i',
        'sine=frequency=440:sample_rate=48000',
        '-t',
        '5',
        '-c:v',
        'libvpx-vp9',
        '-deadline',
        'realtime',
        '-cpu-used',
        '8',
        '-c:a',
        'libopus',
        '-f',
        'webm',
        '-live',
        '1',
        'pipe:1',
      ],
      { shell: false, maxBuffer: 256 << 20, windowsHide: true },
    );
    if (run.status !== 0) throw new Error(`could not generate the test stream: ${run.stderr}`);
    live = run.stdout;
  });
  afterAll(() => {
    fs.rmSync(work, { recursive: true, force: true });
    if (process.env.FRAMECAPT_WRITE_EVIDENCE === '1') {
      writeEvidenceJson(
        path.join(repoRoot, 'docs', 'evidence', 'phase06'),
        'ffmpeg-integration.json',
        evidence,
      );
    }
  });

  /** A fresh root/out per case, and a service that wrote `bytes` as arbitrary chunks. */
  function fresh() {
    counter += 1;
    const root = path.join(work, `root${counter}`);
    const out = path.join(work, `out${counter}`);
    fs.mkdirSync(root, { recursive: true });
    return { root, out, service: new SessionService(root, { diskCheckEveryMs: 0 }) };
  }

  async function feed(service: SessionService, bytes: Buffer, finish: boolean): Promise<number> {
    await service.create(CONFIG, ID, 1);
    const parts = splitArbitrarily(bytes);
    // Overlapping invokes, like a renderer that does not wait: main must keep the order.
    await Promise.all(parts.map((part, seq) => service.append(ID, seq, part, 1)));
    if (finish) await service.finish(ID, parts.length - 1, 1);
    return parts.length;
  }

  /** Decoding the whole file must produce no errors, and a seek in the middle must work. */
  function decodes(file: string): { clean: boolean; seekClean: boolean } {
    const all = spawnSync(
      paths?.ffmpeg ?? '',
      ['-v', 'error', '-i', file, '-fps_mode', 'vfr', '-f', 'null', '-'],
      {
        shell: false,
        encoding: 'utf8',
        windowsHide: true,
      },
    );
    const seek = spawnSync(
      paths?.ffmpeg ?? '',
      ['-v', 'error', '-ss', '2', '-i', file, '-t', '1', '-fps_mode', 'vfr', '-f', 'null', '-'],
      { shell: false, encoding: 'utf8', windowsHide: true },
    );
    return {
      clean: all.status === 0 && all.stderr.trim() === '',
      seekClean: seek.status === 0 && seek.stderr.trim() === '',
    };
  }

  function hasElement(file: string, id: number[]): boolean {
    return fs.readFileSync(file).indexOf(Buffer.from(id)) !== -1;
  }
  const CUES = [0x1c, 0x53, 0xbb, 0x6b];

  it('the generated live stream has no duration and no cues (like MediaRecorder output)', async () => {
    const file = path.join(work, 'live.webm');
    fs.writeFileSync(file, live);
    const probe = await tools.probe(file);
    expect(probe.durationSec).toBeNull();
    expect(hasElement(file, CUES)).toBe(false);
    expect(probe.hasVideo && probe.hasAudio).toBe(true);
  });

  it('arbitrary chunks -> session -> finalize: 1 video + 1 audio stream, duration ~5 s, cues, seekable', async () => {
    const { root, out, service } = fresh();
    const chunks = await feed(service, live, true);
    const done = await service.finalize(ID, { outputDir: out, tools, date: new Date(2026, 9, 2) });

    const probe = await tools.probe(done.outputPath);
    expect(probe.hasVideo).toBe(true);
    expect(probe.hasAudio).toBe(true);
    expect(probe.video).toMatchObject({ width: 640, height: 360, codec: 'vp9' });
    expect(probe.durationSec).toBeGreaterThan(4.9);
    expect(probe.durationSec).toBeLessThan(5.3);
    expect(done.unindexed).toBe(false);
    expect(hasElement(done.outputPath, CUES)).toBe(true);
    expect(decodes(done.outputPath)).toEqual({ clean: true, seekClean: true });
    // every video stream and audio stream really is there (exactly one of each)
    const streams = spawnSync(
      paths?.ffprobe ?? '',
      ['-v', 'error', '-show_entries', 'stream=codec_type', '-of', 'csv=p=0', done.outputPath],
      { shell: false, encoding: 'utf8', windowsHide: true },
    )
      .stdout.trim()
      .split(/\r?\n/)
      .sort();
    expect(streams).toEqual(['audio', 'video']);
    // no duplicate stream, no leftovers next to the export
    expect(fs.existsSync(path.join(root, ID))).toBe(false);
    expect(fs.readdirSync(out)).toEqual([path.basename(done.outputPath)]);
    evidence.finalize = {
      chunks,
      liveBytes: live.length,
      outputBytes: done.bytes,
      durationSec: probe.durationSec,
      cues: true,
      decodeClean: true,
      seekClean: true,
    };
  }, 60_000);

  /** Packet timestamps (ms) per stream, in file order. */
  function packetTimes(file: string): Map<number, number[]> {
    const out = spawnSync(
      paths?.ffprobe ?? '',
      ['-v', 'error', '-show_entries', 'packet=stream_index,pts', '-of', 'csv=p=0', file],
      { shell: false, encoding: 'utf8', windowsHide: true },
    ).stdout;
    const byStream = new Map<number, number[]>();
    for (const line of out.trim().split(/\r?\n/)) {
      const [stream, pts] = line.split(',').map(Number);
      if (stream === undefined || pts === undefined || Number.isNaN(pts)) continue;
      byStream.set(stream, [...(byStream.get(stream) ?? []), pts]);
    }
    return byStream;
  }

  it('MediaRecorder-style duplicate first timestamps (0, 0, 32...) leave the file with strictly increasing ones', async () => {
    // Two frames stamped within the same millisecond, as the browser produces them now and then.
    const generated = spawnSync(
      paths?.ffmpeg ?? '',
      [
        '-hide_banner',
        '-v',
        'error',
        '-f',
        'lavfi',
        '-i',
        'testsrc=size=640x360:rate=30',
        '-f',
        'lavfi',
        '-i',
        'sine=frequency=440:sample_rate=48000',
        '-t',
        '3',
        '-c:v',
        'libvpx-vp9',
        '-deadline',
        'realtime',
        '-cpu-used',
        '8',
        '-c:a',
        'libopus',
        '-bsf:v',
        'setts=pts=if(eq(N\\,1)\\,0\\,PTS):dts=if(eq(N\\,1)\\,0\\,DTS)',
        '-f',
        'webm',
        '-live',
        '1',
        'pipe:1',
      ],
      { shell: false, maxBuffer: 64 << 20, windowsHide: true },
    );
    expect(generated.status, String(generated.stderr)).toBe(0);
    const rawFile = path.join(work, 'dup-first.webm');
    fs.writeFileSync(rawFile, generated.stdout);
    const rawVideo = packetTimes(rawFile).get(0) ?? []; // stream 0 is the video
    expect(rawVideo.slice(0, 2)).toEqual([0, 0]); // the input really has the defect

    const { out, service } = fresh();
    await feed(service, generated.stdout, true);
    const done = await service.finalize(ID, { outputDir: out, tools });
    for (const [stream, times] of packetTimes(done.outputPath)) {
      for (let i = 1; i < times.length; i += 1) {
        expect(times[i] ?? 0, `stream ${stream} packet ${i}`).toBeGreaterThan(times[i - 1] ?? 0);
      }
    }
    const probe = await tools.probe(done.outputPath);
    expect(probe.durationSec).toBeGreaterThan(2.9);
    expect(probe.durationSec).toBeLessThan(3.3);
    expect(probe.hasVideo && probe.hasAudio).toBe(true);
    // No frame was added or dropped: the packet count is the same as in the input.
    const count = (file: string) =>
      [...packetTimes(file).values()].reduce((sum, times) => sum + times.length, 0);
    expect(count(done.outputPath)).toBe(count(rawFile));
  }, 60_000);

  it('a stop that overlaps in-flight chunk writes still produces the complete recording', async () => {
    const { out, service } = fresh();
    await service.create(CONFIG, ID, 1);
    const parts = splitArbitrarily(live, 99);
    const appends = parts.map((part, seq) => service.append(ID, seq, part, 1));
    const stopping = service.markStopping(ID);
    const finishing = service.finish(ID, parts.length - 1, 1);
    const finalizing = service.finalize(ID, { outputDir: out, tools });
    await Promise.all([...appends, stopping, finishing]);
    const done = await finalizing;
    const probe = await tools.probe(done.outputPath);
    expect(probe.durationSec).toBeGreaterThan(4.9);
    expect(decodes(done.outputPath).clean).toBe(true);
  }, 60_000);

  /** Crash simulation: write a truncated stream, "die" (close files, never finish), recover. */
  async function crashAndRecover(fraction: number) {
    const { root, out, service } = fresh();
    const cut = Math.floor(live.length * fraction);
    await feed(service, live.subarray(0, cut), false);
    await service.closeAll(); // the process is gone: no finish, no finalize
    expect(JSON.parse(fs.readFileSync(path.join(root, ID, 'manifest.json'), 'utf8')).state).toBe(
      'recording',
    );
    const recovery = new RecoveryService({
      rootDir: root,
      fs: nodeSessionFs,
      tools,
      outputDir: () => out,
      isActive: () => false,
    });
    const candidates = await recovery.list();
    expect(candidates).toHaveLength(1);
    expect(candidates[0]?.bytes).toBe(cut);
    return { root, out, recovery, outcome: await recovery.recover(ID) };
  }

  it('truncated at 60%: recovery yields a playable file of about 60% of the duration', async () => {
    const { out, outcome } = await crashAndRecover(0.6);
    if (outcome.outcome !== 'recovered') throw new Error('not recovered');
    const probe = await tools.probe(outcome.outputPath);
    expect(probe.durationSec).toBeGreaterThanOrEqual(2.5);
    expect(probe.durationSec).toBeLessThanOrEqual(3.2);
    expect(probe.hasVideo && probe.hasAudio).toBe(true);
    expect(decodes(outcome.outputPath).clean).toBe(true);
    expect(path.basename(outcome.outputPath)).toMatch(/\(recovered\)\.webm$/);
    expect(fs.readdirSync(out)).toHaveLength(1);
    evidence.truncate60 = { durationSec: probe.durationSec, expectedSec: 3 };
  }, 60_000);

  it('measured: how much survives a cut at 10%, 30%, 60% and 90% of the bytes', async () => {
    const rows: Record<string, unknown>[] = [];
    for (const fraction of [0.1, 0.3, 0.9]) {
      const { outcome } = await crashAndRecover(fraction);
      if (outcome.outcome !== 'recovered') {
        rows.push({ fraction, recovered: false });
        continue;
      }
      const probe = await tools.probe(outcome.outputPath);
      rows.push({
        fraction,
        recovered: true,
        durationSec: probe.durationSec,
        decodeClean: decodes(outcome.outputPath).clean,
      });
      // never longer than what was written, and not a tiny fraction of it
      expect(probe.durationSec ?? 0).toBeLessThanOrEqual(5 * fraction + 0.6);
      expect(probe.durationSec ?? 0).toBeGreaterThanOrEqual(5 * fraction - 1.2);
    }
    evidence.truncationSweep = rows;
  }, 120_000);

  it('a stream cut inside the header cannot be repaired: reported honestly, raw data kept', async () => {
    const { root, out, outcome } = await crashAndRecover(0.001); // about 180 bytes
    expect(outcome.outcome).toBe('unrecoverable');
    expect(fs.existsSync(path.join(root, ID, 'stream.webm'))).toBe(true);
    expect(fs.existsSync(out) ? fs.readdirSync(out) : []).toEqual([]);
    evidence.truncateInHeader = { outcome: outcome.outcome };
  }, 60_000);

  it('a stream that is not a video at all is unrecoverable, never "recovered"', async () => {
    const { root, out, service } = fresh();
    await service.create(CONFIG, ID, 1);
    await service.append(ID, 0, Buffer.from('this is definitely not a webm file '.repeat(50)), 1);
    await service.closeAll();
    const recovery = new RecoveryService({
      rootDir: root,
      fs: nodeSessionFs,
      tools,
      outputDir: () => out,
      isActive: () => false,
    });
    expect((await recovery.recover(ID)).outcome).toBe('unrecoverable');
    expect(fs.existsSync(path.join(root, ID, 'finalize.log'))).toBe(true);
  }, 60_000);

  /** Command lines of every running ffmpeg (used to prove a kill). */
  function runningFfmpegCommandLines(): string {
    if (process.platform !== 'win32') {
      // pgrep -a lists pid + full command line; exit 1 (no match) leaves stdout empty.
      return spawnSync('pgrep', ['-af', 'ffmpeg'], { shell: false, encoding: 'utf8' }).stdout;
    }
    const script =
      'Get-CimInstance Win32_Process -Filter "Name=\'ffmpeg.exe\'" | ForEach-Object { $_.CommandLine }';
    // -EncodedCommand (UTF-16LE base64) keeps the quotes intact: no shell quoting involved.
    const encoded = Buffer.from(script, 'utf16le').toString('base64');
    return spawnSync(
      'powershell.exe',
      ['-NoProfile', '-NonInteractive', '-EncodedCommand', encoded],
      { shell: false, encoding: 'utf8', windowsHide: true },
    ).stdout;
  }

  it('abort really ends a running ffmpeg process (process-tree kill), not just the promise', async () => {
    const marker = `framecapt-kill-test-${process.pid}-${Date.now()}`;
    const controller = new AbortController();
    const running = tools.run(
      [
        '-hide_banner',
        '-v',
        'error',
        '-re', // real time: a 120 s job that really runs for 120 s
        '-f',
        'lavfi',
        '-i',
        'testsrc=size=320x240:rate=30',
        '-metadata',
        `title=${marker}`,
        '-t',
        '120',
        '-f',
        'null',
        '-',
      ],
      { signal: controller.signal },
    );
    const settled = running.then(
      () => 'finished',
      (error: unknown) => (error as FfmpegError).code,
    );
    await new Promise((resolve) => setTimeout(resolve, 1500));
    expect(runningFfmpegCommandLines()).toContain(marker); // it is running
    const abortedAt = Date.now();
    controller.abort();
    expect(await settled).toBe('FFMPEG_ABORTED');
    await new Promise((resolve) => setTimeout(resolve, 800));
    expect(runningFfmpegCommandLines()).not.toContain(marker); // and now it is gone
    expect(Date.now() - abortedAt).toBeLessThan(5000);
    evidence.abortKillsProcess = { processEndedAfterAbort: true };
  }, 60_000);

  it('an aborted real remux kills ffmpeg and leaves the manifest finalizing (restart resumes it)', async () => {
    const { root, out, service } = fresh();
    await feed(service, live, true);
    const controller = new AbortController();
    controller.abort(); // aborted before ffmpeg gets going
    await expect(
      service.finalize(ID, { outputDir: out, tools, signal: controller.signal }),
    ).rejects.toMatchObject({ code: 'FINALIZE_FAILED' });
    const manifestPath = path.join(root, ID, 'manifest.json');
    expect(JSON.parse(fs.readFileSync(manifestPath, 'utf8')).state).toBe('finalizing');

    // "the next start": a leftover partial file of this session is removed and the remux re-run
    fs.mkdirSync(out, { recursive: true });
    fs.writeFileSync(path.join(out, `.framecapt-${ID}.partial.webm`), 'junk from the dead run');
    const recovery = new RecoveryService({
      rootDir: root,
      fs: nodeSessionFs,
      tools,
      outputDir: () => out,
      isActive: () => false,
    });
    const report = await recovery.startup();
    expect(report.resumed).toBe(1);
    const files = fs.readdirSync(out);
    expect(files).toHaveLength(1);
    expect(files[0]).toMatch(/^FrameCapt .*\.webm$/);
    const probe = await tools.probe(path.join(out, files[0] ?? ''));
    expect(probe.durationSec).toBeGreaterThan(4.9);
    expect(fs.existsSync(path.join(root, ID))).toBe(false);
  }, 60_000);
});

describe.skipIf(paths === null)(
  'real ffmpeg: a crafted file cannot make the tools reach the network',
  () => {
    const tools = createMediaTools(() => resolveFfmpeg(location));

    /** A local HTTP server that records every request it receives. */
    async function withServer<T>(body: (url: string, hits: string[]) => Promise<T>): Promise<T> {
      const hits: string[] = [];
      const server = http.createServer((request, response) => {
        hits.push(`${request.method} ${request.url}`);
        response.statusCode = 404;
        response.end();
      });
      await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve));
      const { port } = server.address() as { port: number };
      try {
        return await body(`http://127.0.0.1:${port}`, hits);
      } finally {
        await new Promise((resolve) => server.close(resolve));
      }
    }

    it('a crafted playlist (what a user could re-link) is never fetched by the probe or the export', async () => {
      const work = fs.mkdtempSync(path.join(os.tmpdir(), 'framecapt-ffnet-'));
      try {
        await withServer(async (url, hits) => {
          const text = `#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXTINF:5,
${url}/segment.ts
#EXT-X-ENDLIST
`;
          const playlist = path.join(work, 'evil.m3u8');
          const disguised = path.join(work, 'evil.webm');
          fs.writeFileSync(playlist, text);
          fs.writeFileSync(disguised, text);
          // Positive control: the same playlist, with the network protocols allowed, is fetched.
          await tools
            .run(
              [
                '-hide_banner',
                '-v',
                'error',
                '-allowed_extensions',
                'ALL',
                '-protocol_whitelist',
                'file,http,tcp,hls',
                '-i',
                playlist,
                '-f',
                'null',
                '-',
              ],
              { timeoutMs: 15_000 },
            )
            .catch(() => undefined);
          expect(
            hits.length,
            'control: an unrestricted ffmpeg fetches the segment',
          ).toBeGreaterThan(0);
          hits.length = 0;
          // The app's own commands: nothing is requested, and nothing is produced.
          await expect(tools.probe(playlist, { timeoutMs: 15_000 })).rejects.toBeInstanceOf(
            FfmpegError,
          );
          for (const source of [playlist, disguised]) {
            const out = path.join(work, `out-${path.basename(source)}.mp4`);
            const result = await tools
              .run(mp4Args(source, out), { timeoutMs: 15_000 })
              .catch(() => ({ code: -1 }));
            expect(result.code).not.toBe(0);
            expect(fs.existsSync(out)).toBe(false);
          }
          expect(hits, 'probe and export made no request').toEqual([]);
        });
      } finally {
        fs.rmSync(work, { recursive: true, force: true });
      }
    }, 60_000);
  },
);
